<?php

namespace Database\Factories;

use App\Models\DepositRequest;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/** @extends Factory<DepositRequest> */
class DepositRequestFactory extends Factory
{
    protected $model = DepositRequest::class;

    public function definition(): array
    {
        return [
            'user_id' => User::factory(),
            'amount' => fake()->randomFloat(2, 100, 10000),
            // reference_code is auto-generated by model's creating event
            'status' => 'pending',
            'admin_note' => null,
            'confirmed_at' => null,
        ];
    }
}
